### ISSUE TITLE
Пошук книжок

### ISSUE THREAD

**Issue by SerhiySkripa** [yatagan/ILS#11]
Any library member should be able to search books by their title, author, subject category as well by the publication date.

**Comment by yatagan** [comment]
В результаті має бути сторінка на сайті,
на якій є форма пошуку (строка вводу) куди користувач вводить критерій пошуку
і натиснувши кнопку отримує результуючий список книг.

**Comment by yatagan** [comment]
Результат має бути у вигляді Pull request, одного спільного, або двох індивідуальних
